In [1]:
!wget https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
!unzip zomato_dataset.zip
!mv zomato_dataset.csv.

--2026-01-14 15:53:56--  https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/100/375/original/zomato_dataset.zip
Resolving d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)... 3.165.84.59, 3.165.84.114, 3.165.84.173, ...
Connecting to d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)|3.165.84.59|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 72602133 (69M) [application/zip]
Saving to: ‘zomato_dataset.zip’

zomato_dataset.zip  100%[===================>]  69.24M   305MB/s    in 0.2s

2026-01-14 15:53:57 (305 MB/s) - ‘zomato_dataset.zip’ saved [72602133/72602133]

Archive:  zomato_dataset.zip
  inflating: zomato_dataset.csv
mv: missing destination file operand after 'zomato_dataset.csv.'
Try 'mv --help' for more information.

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('/content/zomato_dataset.csv')

In [4]:
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          23193 non-null  object
 1   address                      23193 non-null  object
 2   name                         23193 non-null  object
 3   online_order                 23193 non-null  object
 4   book_table                   23193 non-null  object
 5   rate                         23193 non-null  object
 6   votes                        23193 non-null  int64
 7   phone                        23193 non-null  object
 8   location                     23193 non-null  object
 9   rest_type                    23193 non-null  object
 10  dish_liked                   23193 non-null  object
 11  cuisines                     23193 non-null  object
 12  approx_cost(for two people)  23193 non-null  object
 13  reviews_list                 23193 non-null  object
 14  menu_item                    23193 non-null  object
 15  listed_in(type)              23193 non-null  object
 16  listed_in(city)              23193 non-null  object
dtypes: int64(1), object(16)
memory usage: 3.0+ MB

In [6]:
df.shape

(23193, 17)

In [7]:
df.describe()

              votes
count  23193.000000
mean     601.074462
std     1114.854301
min        0.000000
25%      101.000000
50%      221.000000
75%      586.000000
max    16832.000000

In [11]:
df.describe(include='all')

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
count,23193,23193,23193,23193,23193,23193,23193.000000,23193,23193,23193,23193,23193,23193,23193,23193,23193,23193
unique,23193,4371,3159,2,2,63,NaN,6809,88,73,5189,1687,57,13998,5026,7,30
top,https://www.zomato.com/bangalore/chime-sherato...,"The Ritz-Carlton, 99, Residency Road, Bangalore",Onesta,Yes,No,3.9/5,NaN,080 33994444,Koramangala 5th Block,Casual Dining,Biryani,North Indian,'400.0',[],[],Delivery,BTM
freq,1,51,85,16358,17071,1689,NaN,57,1783,7349,181,1144,2467,176,16414,10625,1423
mean,NaN,NaN,NaN,NaN,NaN,NaN,601.074462,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,1114.854301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,101.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,221.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,586.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,16832.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
data_stats = df.describe()

In [13]:
data_stats.loc['mean']

votes    601.074462
Name: mean, dtype: float64

In [8]:
data = {
    "Restaurant": ["R1", "R2", "R3", "R4"],
    "Votes": [120, 240, 150, 80],
    "Rating": [4.1, 4.5, 3.9, 4.0]
}

sample_df = pd.DataFrame(data)
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
3         R4     80     4.0

In [9]:
sample_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Restaurant  4 non-null      object
 1   Votes       4 non-null      int64
 2   Rating      4 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 228.0+ bytes

In [10]:
sample_df.describe()

            Votes    Rating
count    4.000000  4.000000
mean   147.500000  4.125000
std     68.007353  0.262996
min     80.000000  3.900000
25%    110.000000  3.975000
50%    135.000000  4.050000
75%    172.500000  4.200000
max    240.000000  4.500000

In [14]:
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [15]:
df["approx_cost(for two people)"]

0         '800.0'
1         '800.0'
2         '800.0'
3         '300.0'
4         '600.0'
           ...
23188    '1200.0'
23189    '2000.0'
23190    '1200.0'
23191     '800.0'
23192    '2500.0'
Name: approx_cost(for two people), Length: 23193, dtype: object

In [16]:
df[['approx_cost(for two people)', 'votes']]

      approx_cost(for two people)  votes
0                         '800.0'    775
1                         '800.0'    787
2                         '800.0'    918
3                         '300.0'     88
4                         '600.0'    166
...                           ...    ...
23188                    '1200.0'    128
23189                    '2000.0'     77
23190                    '1200.0'    161
23191                     '800.0'     81
23192                    '2500.0'    236

[23193 rows x 2 columns]

In [18]:
df.loc[:,['approx_cost(for two people)', 'votes']]

      approx_cost(for two people)  votes
0                         '800.0'    775
1                         '800.0'    787
2                         '800.0'    918
3                         '300.0'     88
4                         '600.0'    166
...                           ...    ...
23188                    '1200.0'    128
23189                    '2000.0'     77
23190                    '1200.0'    161
23191                     '800.0'     81
23192                    '2500.0'    236

[23193 rows x 2 columns]

In [21]:
df.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [23]:
df.iloc[:, [12, 11]]

      approx_cost(for two people)                                     cuisines
0                         '800.0'               North Indian, Mughlai, Chinese
1                         '800.0'                  Chinese, North Indian, Thai
2                         '800.0'                       Cafe, Mexican, Italian
3                         '300.0'                   South Indian, North Indian
4                         '600.0'                     North Indian, Rajasthani
...                           ...                                          ...
23188                    '1200.0'     North Indian, Continental, Mediterranean
23189                    '2000.0'                                  Finger Food
23190                    '1200.0'           Chinese, Continental, North Indian
23191                     '800.0'  Andhra, South Indian, Chinese, North Indian
23192                    '2500.0'                                  Finger Food

[23193 rows x 2 columns]

In [26]:
df.rate

0         4.1/5
1         4.1/5
2         3.8/5
3         3.7/5
4         3.8/5
          ...
23188    3.8 /5
23189    3.9 /5
23190    2.8 /5
23191    2.5 /5
23192    4.3 /5
Name: rate, Length: 23193, dtype: object

In [ ]:
#inplace

In [58]:
import pandas as pd

ndf = pd.DataFrame({
    "name": ["A", "B", "C", "D"],
    "rating": [5, None, 4, None],
    "city": ["Mumbai", "Delhi", "Mumbai", "Pune"]
})

print(ndf)

  name  rating    city
0    A     5.0  Mumbai
1    B     NaN   Delhi
2    C     4.0  Mumbai
3    D     NaN    Pune

In [59]:
ndf= ndf.drop('city', axis = 1)

In [57]:
ndf.drop('city', axis = 1)

KeyError: "['city'] not found in axis"

In [49]:
ndf

  name  rating
0    A     5.0
1    B     NaN
2    C     4.0
3    D     NaN

In [28]:
ndf['rating'].fillna(0)

0    5.0
1    0.0
2    4.0
3    0.0
Name: rating, dtype: float64

In [31]:
ndf.fillna(0, inplace = True)

In [32]:
ndf

  name  rating    city
0    A     5.0  Mumbai
1    B     0.0   Delhi
2    C     4.0  Mumbai
3    D     0.0    Pune

In [35]:
ndf['rating'].fillna(0)

0    5.0
1    0.0
2    4.0
3    0.0
Name: rating, dtype: float64

In [37]:
ndf['rating'] = ndf['rating'].fillna(0)

In [38]:
ndf

  name  rating    city
0    A     5.0  Mumbai
1    B     0.0   Delhi
2    C     4.0  Mumbai
3    D     0.0    Pune

In [43]:
df = df.rename(columns={"approx_cost(for two people)":'cost_for_two',"votes": "Total_Votes", "rate": "Ratings"})

In [45]:
df.head()

,url,address,name,online_order,book_table,Ratings,Total_Votes,phone,location,rest_type,dish_liked,cuisines,cost_for_two,reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",'800.0',"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",'800.0',"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",'800.0',"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",'300.0',"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",'600.0',"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [62]:
df['only_rating']= df['Ratings'].str[:-2]

In [64]:
df['only_rating'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 23193 entries, 0 to 23192
Series name: only_rating
Non-Null Count  Dtype
--------------  -----
23193 non-null  object
dtypes: object(1)
memory usage: 181.3+ KB

In [66]:
df['only_rating'] = df['only_rating'].replace('N', np.nan)

In [68]:
df['only_rating']  = df['only_rating'].astype('float')

In [69]:
df['only_rating'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 23193 entries, 0 to 23192
Series name: only_rating
Non-Null Count  Dtype
--------------  -----
23046 non-null  float64
dtypes: float64(1)
memory usage: 181.3 KB

In [70]:
df['cost_for_two']

0         '800.0'
1         '800.0'
2         '800.0'
3         '300.0'
4         '600.0'
           ...
23188    '1200.0'
23189    '2000.0'
23190    '1200.0'
23191     '800.0'
23192    '2500.0'
Name: cost_for_two, Length: 23193, dtype: object

In [76]:
df['cost_for_two'] = pd.to_numeric(df['cost_for_two'].str.strip("'\""), errors= "coerce")

In [ ]:
df['cost_for_two'].str.strip("'\"")

In [77]:
df['cost_for_two'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 23193 entries, 0 to 23192
Series name: cost_for_two
Non-Null Count  Dtype
--------------  -----
23193 non-null  float64
dtypes: float64(1)
memory usage: 181.3 KB

In [79]:
df['cost_for_one'] = df['cost_for_two']/2

In [82]:
df['is_good'] = df['only_rating'] > 4

In [83]:
df.head()

,url,address,name,online_order,book_table,Ratings,Total_Votes,phone,location,rest_type,dish_liked,cuisines,cost_for_two,reviews_list,menu_item,listed_in(type),listed_in(city),only_rating,cost_for_one,is_good
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,4.1,400.0,True
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,4.1,400.0,True
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,3.8,400.0,False
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,3.7,150.0,False
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,3.8,300.0,False

In [81]:
df['only_rating'] > 4

0         True
1         True
2        False
3        False
4        False
         ...
23188    False
23189    False
23190    False
23191    False
23192     True
Name: only_rating, Length: 23193, dtype: bool

In [84]:
df['location'].unique()

array(['Banashankari', 'Basavanagudi', 'Jayanagar', 'Kumaraswamy Layout',
       'Rajarajeshwari Nagar', 'Mysore Road', 'Uttarahalli',
       'South Bangalore', 'Vijay Nagar', 'Bannerghatta Road', 'JP Nagar',
       'BTM', 'Wilson Garden', 'Koramangala 5th Block', 'Shanti Nagar',
       'Richmond Road', 'City Market', 'Bellandur', 'Sarjapur Road',
       'Marathahalli', 'HSR', 'Old Airport Road', 'Indiranagar',
       'Koramangala 1st Block', 'East Bangalore', 'MG Road',
       'Brigade Road', 'Lavelle Road', 'Church Street', 'Ulsoor',
       'Residency Road', 'Shivajinagar', 'Infantry Road',
       'St. Marks Road', 'Cunningham Road', 'Race Course Road', 'Domlur',
       'Koramangala 8th Block', 'Frazer Town', 'Ejipura', 'Vasanth Nagar',
       'Jeevan Bhima Nagar', 'Old Madras Road', 'Commercial Street',
       'Koramangala 6th Block', 'Majestic', 'Langford Town',
       'Koramangala 7th Block', 'Brookefield', 'Whitefield',
       'ITPL Main Road, Whitefield', 'Varthur Main Road, Whitefield',
       'Koramangala 2nd Block', 'Koramangala 3rd Block',
       'Koramangala 4th Block', 'Koramangala', 'Bommanahalli',
       'Hosur Road', 'Seshadripuram', 'Electronic City', 'Banaswadi',
       'North Bangalore', 'RT Nagar', 'Kammanahalli', 'Hennur',
       'HBR Layout', 'Kalyan Nagar', 'Thippasandra', 'CV Raman Nagar',
       'Kaggadasapura', 'Kanakapura Road', 'Nagawara', 'Rammurthy Nagar',
       'Sankey Road', 'Central Bangalore', 'Malleshwaram',
       'Sadashiv Nagar', 'Basaveshwara Nagar', 'Rajajinagar',
       'New BEL Road', 'West Bangalore', 'Yeshwantpur', 'Sanjay Nagar',
       'Sahakara Nagar', 'Jalahalli', 'Yelahanka', 'Magadi Road',
       'KR Puram'], dtype=object)

In [85]:
df['location'].nunique()

88

In [87]:
df['name'].value_counts()

name
Onesta               85
Empire Restaurant    69
KFC                  59
McDonald's           57
Pizza Hut            56
                     ..
Bao & Grills          1
Gongura               1
Tuk-Tuk               1
Karibu - The Zuri     1
Fujian Express        1
Name: count, Length: 3159, dtype: int64

In [ ]:
## Select the first two rows and the first two columns

In [88]:
df.iloc[0:2, 0:2]

,url,address
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ..."
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ..."

In [89]:
# Example DataFrame
data = {
    "Restaurant": ["R1", "R2", "R3", "R4"],
    "Votes": [120, 240, 150, 80],
    "Rating": [4.1, 4.5, 3.9, 4.0]
}

sample_df = pd.DataFrame(data)

In [94]:
sample_df.iloc[1:3,1:3] = [[300, 4.7], [180, 4.2]]

In [95]:
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    300     4.7
2         R3    180     4.2
3         R4     80     4.0

In [96]:
df['flag'] = 1

In [97]:
df.head()

,url,address,name,online_order,book_table,Ratings,Total_Votes,phone,location,rest_type,...,cuisines,cost_for_two,reviews_list,menu_item,listed_in(type),listed_in(city),only_rating,cost_for_one,is_good,flag
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,...,"North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,4.1,400.0,True,1
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,...,"Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,4.1,400.0,True,1
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining",...,"Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,3.8,400.0,False,1
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,...,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,3.7,150.0,False,1
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,...,"North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,3.8,300.0,False,1

In [98]:
df_explicit = df.set_index("name")

In [99]:
df_explicit.head()

,url,address,online_order,book_table,Ratings,Total_Votes,phone,location,rest_type,dish_liked,cuisines,cost_for_two,reviews_list,menu_item,listed_in(type),listed_in(city),only_rating,cost_for_one,is_good,flag
name,,,,,,,,,,,,,,,,,,,,
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,4.1,400.0,True,1
Spice Elephant,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,4.1,400.0,True,1
San Churro Cafe,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,3.8,400.0,False,1
Addhuri Udupi Bhojana,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,3.7,150.0,False,1
Grand Village,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,3.8,300.0,False,1

In [102]:
df_explicit.loc['Jalsa','flag']= 0

In [103]:
df_explicit.loc['Jalsa','flag']

name
Jalsa    0
Jalsa    0
Jalsa    0
Jalsa    0
Jalsa    0
Jalsa    0
Jalsa    0
Jalsa    0
Jalsa    0
Jalsa    0
Jalsa    0
Name: flag, dtype: int64

In [106]:
df_explicit.loc[df_explicit["only_rating"]< 3, 'flag'] = -1

In [112]:
df_explicit.loc[df_explicit["only_rating"]< 3, 'flag']

name
Foodiction               -1
Nandhini Deluxe          -1
Dal Tadkaa               -1
Ugadi                    -1
The Chaat Shop           -1
                         ..
Chung Wah                -1
Shaan-E-Punjab           -1
Bhagini                  -1
Keys Cafe - Keys Hotel   -1
Bhagini                  -1
Name: flag, Length: 1174, dtype: int64

In [113]:
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    300     4.7
2         R3    180     4.2
3         R4     80     4.0

In [114]:
data2 = {
    "Restaurant": ["R5", "R6"],
    "Votes": [90, 110],
    "Rating": [3.8, 4.3]
}

df2 = pd.DataFrame(data2)

In [115]:
df2

  Restaurant  Votes  Rating
0         R5     90     3.8
1         R6    110     4.3

In [118]:
combined_df = pd.concat([sample_df, df2], ignore_index= True)

In [119]:
combined_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    300     4.7
2         R3    180     4.2
3         R4     80     4.0
4         R5     90     3.8
5         R6    110     4.3

In [120]:
new_columns = {
    "Delivery Time (mins)": [30, 25, 35, 20, 40, 28]
}

df_new_cols = pd.DataFrame(new_columns)

In [121]:
df_new_cols

   Delivery Time (mins)
0                    30
1                    25
2                    35
3                    20
4                    40
5                    28

In [123]:
pd.concat([combined_df, df_new_cols ], axis = 1)

  Restaurant  Votes  Rating  Delivery Time (mins)
0         R1    120     4.1                    30
1         R2    300     4.7                    25
2         R3    180     4.2                    35
3         R4     80     4.0                    20
4         R5     90     3.8                    40
5         R6    110     4.3                    28

In [125]:
import pandas as pd

df3 = pd.DataFrame({
    "city": ["Mumbai", "Delhi", "Mumbai", "Pune", "Delhi", "Mumbai"]
})

In [127]:
df3.value_counts()

city
Mumbai    3
Delhi     2
Pune      1
Name: count, dtype: int64

In [140]:
df4 = pd.DataFrame({
    "cost": [" '1200' ", '"850"', " 600 ", "unknown"]
})

df4

       cost
0   '1200'
1     "850"
2      600
3   unknown

In [143]:
pd.to_numeric(df4["cost"].str.strip("" \ '"),errors= "coerce")

0      NaN
1    850.0
2    600.0
3      NaN
Name: cost, dtype: float64

In [147]:
df4['cost'].str.strip().str.strip("'").str.strip('"')

0       1200
1        850
2        600
3    unknown
Name: cost, dtype: object

In [138]:
df4

0     '1200'
1         850
2        600
3     unknown
Name: cost, dtype: object